// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `empty`, `from_manifest`, `short_hex`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `FfiError`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// Verify an Oversight `.oversight` bundle entirely offline.
///
/// `bundle_bytes` is the raw `.oversight` file (read from disk by the Flutter
/// layer and handed to us). Returns a structured result the UI renders.
///
/// This is a synchronous function — verification is pure crypto on bytes
/// already in memory, so we avoid the async / executor cost on the mobile
/// thread. Flutter callers should still invoke off the UI thread for large
/// bundles.
Future<VerifyResult> verifyBundle({required List<int> bundleBytes}) =>
    RustLib.instance.api.crateApiVerifyVerifyBundle(bundleBytes: bundleBytes);

/// Library version, surfaced to the Flutter UI for diagnostics + bug reports.
Future<String> libraryVersion() =>
    RustLib.instance.api.crateApiVerifyLibraryVersion();

/// FFI smoke test — verifies the toolchain wiring works end-to-end without
/// requiring any input bytes. Useful as the first call from Dart on app boot
/// so a broken native lib surfaces immediately, not on first user action.
Future<String> smokeTest() => RustLib.instance.api.crateApiVerifySmokeTest();

/// Subset of the manifest safe to surface in a UI. We deliberately do NOT
/// surface the recipient public key in plaintext on a phone screen — only its
/// short hash form (matches the public Rekor predicate).
class ManifestSummary {
  final String fileId;
  final String issuerId;
  final String issuerPubkeyShort;
  final String originalFilename;
  final String contentType;
  final String contentHashShort;
  final BigInt sizeBytes;
  final PlatformInt64 issuedAtUnix;
  final String suite;
  final BigInt watermarkCount;
  final bool hasRecipient;

  const ManifestSummary({
    required this.fileId,
    required this.issuerId,
    required this.issuerPubkeyShort,
    required this.originalFilename,
    required this.contentType,
    required this.contentHashShort,
    required this.sizeBytes,
    required this.issuedAtUnix,
    required this.suite,
    required this.watermarkCount,
    required this.hasRecipient,
  });

  @override
  int get hashCode =>
      fileId.hashCode ^
      issuerId.hashCode ^
      issuerPubkeyShort.hashCode ^
      originalFilename.hashCode ^
      contentType.hashCode ^
      contentHashShort.hashCode ^
      sizeBytes.hashCode ^
      issuedAtUnix.hashCode ^
      suite.hashCode ^
      watermarkCount.hashCode ^
      hasRecipient.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ManifestSummary &&
          runtimeType == other.runtimeType &&
          fileId == other.fileId &&
          issuerId == other.issuerId &&
          issuerPubkeyShort == other.issuerPubkeyShort &&
          originalFilename == other.originalFilename &&
          contentType == other.contentType &&
          contentHashShort == other.contentHashShort &&
          sizeBytes == other.sizeBytes &&
          issuedAtUnix == other.issuedAtUnix &&
          suite == other.suite &&
          watermarkCount == other.watermarkCount &&
          hasRecipient == other.hasRecipient;
}

class VerifyResult {
  final VerifyStatus status;
  final BigInt bundleSizeBytes;
  final ManifestSummary manifest;
  final bool signatureValid;

  /// Human-readable failure reasons. Empty when status == Ok.
  final List<String> failures;

  const VerifyResult({
    required this.status,
    required this.bundleSizeBytes,
    required this.manifest,
    required this.signatureValid,
    required this.failures,
  });

  @override
  int get hashCode =>
      status.hashCode ^
      bundleSizeBytes.hashCode ^
      manifest.hashCode ^
      signatureValid.hashCode ^
      failures.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VerifyResult &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          bundleSizeBytes == other.bundleSizeBytes &&
          manifest == other.manifest &&
          signatureValid == other.signatureValid &&
          failures == other.failures;
}

enum VerifyStatus {
  /// All checks passed.
  ok,

  /// Bundle parsed but signature did not verify or required field missing.
  fail,
}
